/*
 * Copyright (c) HEROW 2021.
 */

import { WithPrecisionColumnType } from 'typeorm/driver/types/ColumnTypes';

// Format of autogenerated timestamps in entities
export const TIMESTAMP_FORMAT: WithPrecisionColumnType = 'timestamp';

export const SWAGGER_URL_PATH = '/documentation';

// Url cache time to live
export const URL_CACHE_TTL_SEC = 3600;

// Length of url hash
export const URL_HASH_LENGTH = 6;
